### ISSUE TITLE
GLI Formats and Vulkan

### ISSUE THREAD

**Issue by Unarmed1000** [g-truc/gli#104]
Are the GLI formats supposed to be compatible with the vulkan formats?
Take
  gli::FORMAT_RGB9E5_UFLOAT_PACK32

A obvious candidate in vulkan would be
  VK_FORMAT_E5B9G9R9_UFLOAT_PACK32

But the byte ordering would not be the same since Vulkan is E5B9G9R9 vs RGB9E5 which I suppose is R9G9B9E5.

But most's formats seem to be compatible like
 FORMAT_RG4_UNORM_PACK8 == VK_FORMAT_R4G4_UNORM_PACK8

However these do not appear to match anything in Vulkan and the Vulkan formats are not present in gli.
Just listing the unorm variants here:
- FORMAT_RGBA8_UNORM_PACK32  != VK_FORMAT_RGBA8_UNORM_PACK32
- FORMAT_RGB10A2_UNORM_PACK32 != VK_FORMAT_A2R10G10B10_UNORM_PACK32
- FORMAT_BGR10A2_UNORM_PACK32 != VK_FORMAT A2B10G10R10_UNORM_PACK32
- FORMAT_RG11B10_UFLOAT_PACK32 != VK_FORMAT_B10G11R11_UFLOAT_PACK32
- FORMAT_RGB9E5_UFLOAT_PACK32 != VK_FORMAT_E5B9G9R9_UFLOAT_PACK32

In general it would be nice if these were more explicit and commented, matching the compressed formats is non-trivial too.

**Comment by Unarmed1000** [comment]
Finished going through all the vulkan formats and these were the ones I had problems mapping
VK_FORMAT_A8B8G8R8_UNORM_PACK32:
VK_FORMAT_A8B8G8R8_SNORM_PACK32:
VK_FORMAT_A8B8G8R8_USCALED_PACK32:
VK_FORMAT_A8B8G8R8_SSCALED_PACK32:
VK_FORMAT_A8B8G8R8_UINT_PACK32:
VK_FORMAT_A8B8G8R8_SINT_PACK32:
VK_FORMAT_A8B8G8R8_SRGB_PACK32:
VK_FORMAT_A2R10G10B10_UNORM_PACK32:
VK_FORMAT_A2R10G10B10_SNORM_PACK32:
VK_FORMAT_A2R10G10B10_USCALED_PACK32:
VK_FORMAT_A2R10G10B10_SSCALED_PACK32:
VK_FORMAT_A2R10G10B10_UINT_PACK32:
VK_FORMAT_A2R10G10B10_SINT_PACK32:
VK_FORMAT_A2B10G10R10_UNORM_PACK32:
VK_FORMAT_A2B10G10R10_SNORM_PACK32:
VK_FORMAT_A2B10G10R10_USCALED_PACK32:
VK_FORMAT_A2B10G10R10_SSCALED_PACK32:
VK_FORMAT_A2B10G10R10_UINT_PACK32:
VK_FORMAT_A2B10G10R10_SINT_PACK32:
VK_FORMAT_B10G11R11_UFLOAT_PACK32:
VK_FORMAT_E5B9G9R9_UFLOAT_PACK32:
VK_FORMAT_X8_D24_UNORM_PACK32:
VK_FORMAT_D16_UNORM_S8_UINT:
VK_FORMAT_D24_UNORM_S8_UINT:
VK_FORMAT_D32_SFLOAT_S8_UINT:
VK_FORMAT_BC1_RGB_UNORM_BLOCK:
VK_FORMAT_BC1_RGB_SRGB_BLOCK:
VK_FORMAT_BC1_RGBA_UNORM_BLOCK:
VK_FORMAT_BC1_RGBA_SRGB_BLOCK:
VK_FORMAT_BC2_UNORM_BLOCK:
VK_FORMAT_BC2_SRGB_BLOCK:
VK_FORMAT_BC3_UNORM_BLOCK:
VK_FORMAT_BC3_SRGB_BLOCK:
VK_FORMAT_BC4_UNORM_BLOCK:
VK_FORMAT_BC4_SNORM_BLOCK:
VK_FORMAT_BC5_UNORM_BLOCK:
VK_FORMAT_BC5_SNORM_BLOCK:
VK_FORMAT_BC6H_UFLOAT_BLOCK:
VK_FORMAT_BC6H_SFLOAT_BLOCK:
VK_FORMAT_BC7_UNORM_BLOCK:
VK_FORMAT_BC7_SRGB_BLOCK:
VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK:
VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK:
VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK:
VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK:
VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK:
VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK:
VK_FORMAT_EAC_R11_UNORM_BLOCK:
VK_FORMAT_EAC_R11_SNORM_BLOCK:
VK_FORMAT_EAC_R11G11_UNORM_BLOCK:
VK_FORMAT_EAC_R11G11_SNORM_BLOCK:

Most of them seems to have something similar but not quite the same in gli.

**Comment by Groovounet** [comment]
Yes GLI enum match VUlkan one.

Thanks,
Christophe

**Comment by Unarmed1000** [comment]
You really should consider fixing the ORDER of the components then in the ones I pointed out. As the order in your enum suggest a ordering of the components. Where Vulkan is correct.
