### ISSUE TITLE
Investigate possible license issue with GPL in shared_ptr.inl

### ISSUE THREAD

**Issue by sschuberth** [g-truc/gli#114]
I realized [shared_ptr.inl is GPL-licensed](https://github.com/g-truc/gli/blob/eeacba75b7d564f93a560b1999ff877fad51592b/external/glm/test/external/gli/core/shared_ptr.inl#L4). If that's correct, how does that affect licensing `gli` under the "Happy Bunny" license? At least [this issue](https://github.com/g-truc/glm/issues/511) claims the "Happy Bunny" license to be "non-free" and thus incompatible with GPL. I have no idea whether that's actually correct.

In any case, people might be willing to use `gli` under (modified) MIT in their code, but as they will get GPL-licensed code with it, my current understanding is that all code using `gli` will be under GPL then. Is that correct?

If so, is there any way to replace `shared_ptr.inl` e.g. with [std::shared_ptr](http://en.cppreference.com/w/cpp/memory/shared_ptr)?

**Comment by Groovounet** [comment]
The code you refer is only used in GLM test code and rely on GLI 0.3 which is really old. 

I guess this might only mean I should upgrade GLI code in GLM...

Thanks for reporting,
Christophe

**Comment by Groovounet** [comment]
This is fixed in GLI and GLM master branch by updating the libraries used for unit tests.

Thanks for reporting,
Christophe
