### ISSUE TITLE
Potential issue with loading BC5 DDS texture format

### ISSUE THREAD

**Issue by presentfactory** [g-truc/gli#121]
While working with GLI earlier today I noticed something seemed to be wrong with a texture I was loading in from the disk (with a DDS format of BC5_UNORM), specifically that it seemed to only load in the first (Red) channel from the image (which I confirmed did indeed have 2 channels on the disk).

After ruling out any of my code, I noticed that while setting the texture parameters for an OpenGL texture object that the swizzles were only set for the red channel, the rest were zero. I traced the problem back to [these lines](https://github.com/g-truc/gli/blob/master/gli/core/format.inl#L203-L204) (lines 203 and 204 of format.inl) where it seems the swizzles for `FORMAT_RG_ATI2N_UNORM_BLOCK16` (and the signed variant) appear to be incorrect unless I am misunderstanding their purpose.

Anyways, changing those line's swizzles to `swizzles(SWIZZLE_RED, SWIZZLE_GREEN, SWIZZLE_ZERO, SWIZZLE_ONE)` seems to fix my problem so I thought I'd report it here in case it helps.

**Comment by amc522** [comment]
Your analysis and fix is correct. I have this fixed in my local branch but haven't merged it in yet. I am not the maintainer, but feel free to make a pull request.

**Comment by Groovounet** [comment]
This issue is fixed in master branch.

Thanks for contributing,
Christophe
