### ISSUE TITLE
BC7 DDS Loading swizzling issue

### ISSUE THREAD

**Issue by presentfactory** [g-truc/gli#122]
I think I have discovered yet another swizzling issue like #121 in the texture loading process. This time I was trying to load a BC7 DDS texture I knew had an alpha channel and was a bit confused when I saw that it did not actually exist when displaying it (instead areas with alpha were solid colors).

After stepping through all of my stuff first and making sure it wasn't any of that I stepped into GLI to ensure that it was generating all of the correct information and I noticed that the alpha swizzle was set to `SWIZZLE_ONE` where from looking at everything else in the same files seems like it should be `SWIZZLE_ALPHA` (the format in question specifically is `FORMAT_RGBA_BP_UNORM_BLOCK16`). The lines in question are [here](https://github.com/g-truc/gli/blob/master/gli/core/format.inl#L207), 207 and 208 currently in format.inl.

If I'm incorrect in assuming that and it's just not supposed to work like that then I'd like to know as well, but after changing what I described it seems to work now.

**Comment by Groovounet** [comment]
This issue was resolved by PR #126.

Thanks for reporting!
Christophe
