### ISSUE TITLE
Get BPP for a specific format

### ISSUE THREAD

**Issue by feliwir** [g-truc/gli#131]
Hey, is there a builtin methods to retrieve the BPP depending on the format? Thanks

**Comment by Groovounet** [comment]
Hi,
There isn't because it doesn't scale well for compressed formats. Instead, GLI has gli::block_size(Format) to figure the size in bytes of a format block of pixels and gli::block_extent(Format) to figure out the number of texels in a block.

> BPP = float(block_size * 8) / float(block_extent.x * block_extent.y * block_extent.z)

Thanks,
Christophe

**Comment by feliwir** [comment]
hi,

the reason i ask this is that D3D11 requires me to specify rowPitch and depthPitch: https://msdn.microsoft.com/de-de/library/windows/desktop/ff476486(v=vs.85).aspx

I am not sure the block_extent function is providing me with those values.
Thanks,
Stephan

**Comment by Groovounet** [comment]
rowPitch = glm::ceilMultiple(textureWidth, gli::block_extent(format).x);

**Comment by feliwir** [comment]
your rowPitch calculation isn't working. I have the following call:
int rowPitch = glm::ceilMultiple(800, gli::block_extent(gli::FORMAT_RGBA8_UNORM_PACK8).x);

The expected rowPitch would be 3200, but i get 800

**Comment by Groovounet** [comment]
rowPitch = glm::ceilMultiple(textureWidth, gli::block_extent(format).x) * block_size(format);

I think it would be useful that you think about what rowPitch is and how to compute it.

**Comment by feliwir** [comment]
Well i figured a calculation out, but according to your calculation above the rowPitch would be 8192, when it truly is2048. See my calculation below:
```
        int BPP = 4;
	if(!gli::is_compressed(tex.format()))
		BPP = gli::block_size(tex.format());
	else
		BPP = gli::block_extent(tex.format()).x;

	std::vector<D3D11_SUBRESOURCE_DATA> initial_data(tex.levels());

	//trigger this for mipmaps
	int level = 0;
	for (auto&& level_data : initial_data)
	{
		glm::tvec3<int> extent(tex.extent(level));
		int rowPitch = extent.x* BPP;
		ZeroMemory(&level_data, sizeof(D3D11_SUBRESOURCE_DATA));
		level_data.pSysMem = tex.data(0, 0, level);
		level_data.SysMemPitch = rowPitch;
		++level;
	}
```
I didn't get it working without the check for compressed/uncompressed.  Maybe I am missing something but none of your calculations were correct yet :D
