### ISSUE TITLE
Incorrect BGRA translation

### ISSUE THREAD

**Issue by Xottab-DUTY** [g-truc/gli#167]
When we are loading a texture with `gli::load` the library correctly detects it's format: `FORMAT_BGRA8_UNORM_PACK8`

But when I use `gli::gl::translate` it returns **wrong** format: `INTERNAL_RGBA8_UNORM` which is leads to...

Just look at the screenshot with GLI 0.8.2.0:
![ss_Султан_05-04-19_16-11-24_(zaton)](https://user-images.githubusercontent.com/2989212/57179596-ec4c0480-6e98-11e9-9f05-fe7b1bb6d79c.jpg)
You see that magic-yellow circles on the water, blue bullet shells?

And see how it should be (screenshot made with GLI 0.8.0.0):
![ss_Султан_05-04-19_18-24-38_(zaton)](https://user-images.githubusercontent.com/2989212/57179720-1d790480-6e9a-11e9-9d9a-700a4a0f3965.jpg)

Test DDS file
[pfx_shells1.zip](https://github.com/g-truc/gli/files/3144400/pfx_shells1.zip)

The bug is in `gli/core/gl.inl`. Here's the history link, it may help someone who wants to fix the bug.
https://github.com/g-truc/gli/commits/master/gli/core/gl.inl

**Comment by alexeysvrv** [comment]
@Groovounet Please consider this issue.

**Comment by legends2k** [comment]
Did apply swizzles correctly using `glTexParameteri` and what's returned by `format.swizzles(...)` as in [this example](http://gli.g-truc.net/0.8.0/api/a00006.html)?

**Comment by eagleivg** [comment]
Thanks for advice, colors apply correct. But now invisible text (incorrect load font texture). Can you say about it?

[ui_font_console_02.dds.zip](https://github.com/g-truc/gli/files/3827729/ui_font_console_02.dds.zip)

**Comment by eagleivg** [comment]
fixed with next code:
```cpp
        if (gli::gl::EXTERNAL_RED != Format.External) // skip for properly greyscale-alpfa fonts textures
        {
            glTexParameteri(Target, GL_TEXTURE_SWIZZLE_R, Format.Swizzles[0]);
            glTexParameteri(Target, GL_TEXTURE_SWIZZLE_G, Format.Swizzles[1]);
            glTexParameteri(Target, GL_TEXTURE_SWIZZLE_B, Format.Swizzles[2]);
            glTexParameteri(Target, GL_TEXTURE_SWIZZLE_A, Format.Swizzles[3]);
        }
```
This ticket can be closed.
