### ISSUE TITLE
Incorrect bit manipulation in DDS/s3tc decoding

### ISSUE THREAD

**Issue by malytomas** [g-truc/gli#176]
https://github.com/g-truc/gli/blob/8e43030b3e12bb58a4663d85adc5c752f89099c0/gli/core/workaround.hpp#L333

This function multiplies with vector (15, 31, 15), but the correct values should be (31, 63, 31).
5 bits can store 32 values and 6 bits can store 64 values.

The unpack function has the same issue.

I did not look at any other functions since I do not use them.

**Comment by christophe-lunarg** [comment]
This code is never used anywhere and was removed. GLM version of packUnorm1x5_1x6_1x5 is used and doesn't have this issue
