### ISSUE TITLE
gl/core/storage.hpp identical to gl/core/storage_linear.hpp

### ISSUE THREAD

**Issue by jstrom2002** [g-truc/gli#179]
It seems the files 'gl/core/storage.hpp' and 'gl/core/storage_linear.hpp' are identical. I'm not sure this is actually an issue or just a change in functionality? Either way, it causes issues with some older code I have that uses the old 'gl::storage' class.

**Comment by Groovounet** [comment]
This issue is solved on master branch.

The idea is to add a twiddled order / Z-order storage at some point (TM)

Thanks for reporting.
