### ISSUE TITLE
gli crashes when loading RG16_UNORM DDS file saved with gli

### ISSUE THREAD

**Issue by Opioid** [g-truc/gli#34]
I save a RG16_UNORM texture with gli. When I try to load the texture again at a later point I get a crash somewhere in gli. It works with the RGBA8_UNORM format for example. This is what I do:

gli::texture2D texture(1, gli::RG16_UNORM, gli::texture2D::dimensions_type(description.dimensions.x, description.dimensions.y));

std::copy(data.buffer, data.buffer + data.num_bytes, texture.data<unsigned char>());

gli::save_dds(texture, name.c_str());

BTW:
I get a little confused by the code sample to save textures with gli at http://gli.g-truc.net/0.5.0/code.html

// Allocated a 32 bits texture with one mipmap level
gli::texture2D Texture(3, gli::RGBA8_UNORM, gli::texture2D::dimensions_type(256, 256));

Is it a typo in the comment, that only one mipmap level is created?

Texture[0].clear(glm::u8vec4(255, 0, 0, 255)));

There is one closing bracket too much.

**Comment by hypernewbie** [comment]
RGB565, 16F and 32F are broken too.

**Comment by Groovounet** [comment]
This issue in fixed in GLI 0.6.0.

Have a look at fetch_rg8_unorm in core_fetch.cpp for a code sample.

Thanks,
Christophe
