### ISSUE TITLE
Please describe more about the features of GLI

### ISSUE THREAD

**Issue by RoestVrijStaal** [g-truc/gli#41]
The word "Image" in the name is misleading. It only supports rare image formats. 

I spend too much time in reading the available docs and the sources to check if  PNG or JPG are supported.

Also, the manual at the project's website http://gli.g-truc.net gives a 404: http://gli.g-truc.net/gli.pdf

**Comment by legends2k** [comment]
I agree, documentation on GLI needs quite some improvement compared to the well-documented GLM.

**Comment by Groovounet** [comment]
The API documentation is being largely improved in GLI 0.8, you can see some initial work here:
http://gli.g-truc.net/0.8.0/api/namespaces.html

GLI is still evolving and the development has been particularly significant during the last year.
Beyond the fact that it needs to be done, this has been a major factor delaying the documentation improvements.

Thanks,
Christophe
