### ISSUE TITLE
Build failure on VS2010 because of non-inlined functions

### ISSUE THREAD

**Issue by afayaz** [g-truc/gli#42]
I've been getting linker errors (LNK2005 already defined) on Visual Studio 2010 on the functions `gli::detail::getMaskRed()`, `gli::detail::getMaskGreen()`, `gli::detail::getMaskBlue()`, and `gli::detail::getMaskAlpha()` when I include `gli.hpp` in more than one file.

This can be easily fixed by changing the functions in `save_dds.inl` to be `inline`, which I assume had been overlooked.

**Comment by Groovounet** [comment]
This issue is fixed in GLI 0.6.0.0.

Thanks for reporting,
Christophe
