### ISSUE TITLE
External format incorrect for DDS ARGB format file

### ISSUE THREAD

**Issue by legends2k** [g-truc/gli#43]
When loading a DDS file which has dwFourCC = 0 but has dwFlags = DDPF_RGB, dwRGBBitCount = 32 then such a file has a pixel format of D3DFMT_X8R8G8B8, where the alpha chanel is ignored (is always 0). However, in such DDS files the data is laid out as BGRX to avoid byte swapping on little endian machines. This can be seen in a hex viewer. Here's such a file: http://www.riemers.net/Downloads/resources/Series4/grass.dds

When GLI reads the file data, it reads a word and thus u8vec4's RGBA memebers get the file's BGRX values. In the storage::load_dds function I see that the R and B components are swapped in a for loop to make sure this difference is corrected and final pixel is of the form RGBA. So far no problem.

But when querying gli::external_type instead of returning (the now corrected format of) RGBA it returns BGRA incorrectly. This is a bug. This has led to the below stackoverflow.com post which has the details and also the link to the DDS file for reproducing the issue.

http://stackoverflow.com/q/27200528/183120

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLI 0.6.1.0 release.

Thanks,
Christophe
