### ISSUE TITLE
load_dds(buffer, size) non-functional

### ISSUE THREAD

**Issue by ovrpete** [g-truc/gli#46]
Hi -- using the method to load a dds file from a buffer does not work.  The core routine (that takes an istream) uses tellg() to figure out how large the file is, but tellg() (and the underlying function seekoff/seekpos) is not implemented when using the imemstream class from stackoverflow -- calling tellg() always returns -1.  This ends up leaving the image buffer all zero!

**Comment by hypernewbie** [comment]
I can repro.

**Comment by hypernewbie** [comment]
Hacky patch here:
https://gist.github.com/hypernewbie/fa3e37b4c1074a3c6ec7

**Comment by ovrpete** [comment]
thanks for the patch -- i did something similar.  i should warn you, i've not filed any of the many additional bugs i've run into with loading anything but the most vanilla formats.  i think you've seen some things already with your reswizzle flag, there are many more problems.

**Comment by hypernewbie** [comment]
thanks for the heads-up. Yeah I know all the bit-packed formats are broken too. So are the swizzled ones.

Would you care to share a quick list of some you found? That would be of a great help.

**Comment by ovrpete** [comment]
Hmm.. off the top of my head: the bitpacked formats and non-4 channel formats like RG, many formats load as UINT/SINT instead of UNORM or SNORM (the table that converts used integer types for most everything), no support for any LUMINANCE textures.  A smattering of byte-order issues (the code that manually swaps 4 channel images runs on images it should not, and doesn't handle other images).  I stopped after a while.

I might suggest looking at microsoft's https://github.com/Microsoft/DirectXTex code, it is pretty good especially support for DX10 feature level images.

**Comment by hypernewbie** [comment]
Thanks for that.
I don't think I'll need those features, so I'll stick with GLI for now.
GLI does seem like a bit of a vegetable though.

**Comment by Groovounet** [comment]
This issue has been fixed in GLI 0.6.0.0 and unit tests have been added,

Thanks for reporting,
Christophe
