### ISSUE TITLE
Floating point formats broken on ToT.

### ISSUE THREAD

**Issue by hypernewbie** [g-truc/gli#47]
F16 and F32 formats are broken.

Hacked up patch to fix this issue here.
https://gist.github.com/hypernewbie/8ffb338b50a4e6c28512

I suggest adding more regression for DDS formats.

**Comment by Groovounet** [comment]
This issue should be fixed already in GLI 0.6.0.0.

Thanks for reporting,
Christophe

**Comment by Groovounet** [comment]
By the way, unit tests have been largely improved to avoid this kind of regressions.

**Comment by hypernewbie** [comment]
thank you
