### ISSUE TITLE
Luminance/Alpha format

### ISSUE THREAD

**Issue by elect86** [g-truc/gli#56]
I think these

https://github.com/g-truc/gli/blob/master/gli/core/gl.inl#L240-L241

```
			{INTERNAL_RG8_UNORM, EXTERNAL_RED, TYPE_U8},							//FORMAT_L8_UNORM,
			{INTERNAL_RGB8_UNORM, EXTERNAL_RED, TYPE_U8},							//FORMAT_A8_UNORM,
```

Should be both `INTERNAL_R8_UNORM` instead

**Comment by Groovounet** [comment]
This issue has been fixed in master branch for GLI 0.7.1 release.

Thanks for reporting,
Christophe
