### ISSUE TITLE
I can't compile it

### ISSUE THREAD

**Issue by elect86** [g-truc/gli#57]
Hi, 

I'm trying to compile it under Windows and Netbeans, but I keep getting this [error](https://gist.github.com/elect86/0eada268cba0cf7114db)

```
/cygdrive/c/Users/GBarbieri/Downloads/gli-0.7.0.0/gli/external/glm-0.9.7.1/glm/detail/func_trigonometric.inl:166:14: error: 'std::asinh' has not been declared
   using std::asinh;
```

**Comment by JesseTG** [comment]
You may need to enable C++11; dunno how exactly to do that through NetBeans, but if you're using `gcc` just pass in the `--std=c++11` flag.
