### ISSUE TITLE
DXGI_FORMAT_B8G8R8X8_UNORM_SRGB returns FORMAT_RGB8_SRGB instead FORMAT_BGRX8_SRGB

### ISSUE THREAD

**Issue by elect86** [g-truc/gli#59]
In the GLI 0.7.0, end of August, I get an error

When I am trying to read the texture `kueken7_bgrx8_srgb.dds` I retrieve the right format `DXGI_FORMAT_B8G8R8X8_UNORM_SRGB`.

In the translation table we have two references of this format, the first one is [here](https://github.com/bagobor/gli/blob/331b3c84fe5f1a1ccc85fefaf795ee0e260a47ff/gli/core/dx.inl#L103) and the second one is [here](https://github.com/bagobor/gli/blob/331b3c84fe5f1a1ccc85fefaf795ee0e260a47ff/gli/core/dx.inl#L119).
But since in the `inline gli::format dx::find(dx::dxgiFormat Format)` we loop the translation table from the top, we will get the first reference as result, that will turn into `FORMAT_RGB8_SRGB` (=50) instead that `FORMAT_BGRX8_SRGB`, this will lead to a wrong exstimated texture size based on 3 components instead of 4 at [this point](https://github.com/bagobor/gli/blob/331b3c84fe5f1a1ccc85fefaf795ee0e260a47ff/gli/core/load_dds.inl#L268), 262'143 instead of 349672 (with 148 B header)

**Comment by Groovounet** [comment]
This issue has been fixed in master branch for next release.

Thanks for contributing!
Christophe

**Comment by elect86** [comment]
Hi Christophe,

thanks for the bugfix, it works now! :)

Ps: I did/doing a java port of your library [here](https://github.com/elect86/jgli), may I ask you to add it on your readme to redirect the java users and so that I can start gathering some feedbacks?

**Comment by Groovounet** [comment]
Oohhh, really nice! Sure I can. 

It's pretty unfortunate that GLI code is still evolving pretty quickly. Master branch is already pretty different from GLI 0.7.... 

Thanks for contributing!
Christophe

**Comment by elect86** [comment]
Oh, I am really glad you appreciated!

Yeah, I know, you are really pushing it I see :)

Anyway, I'll synchronize mine with your from time to time, comparing your commits and finding out the difference makes it quite feasible
