### ISSUE TITLE
dds_load fails loading uncompressed RGBA8 texture

### ISSUE THREAD

**Issue by legends2k** [g-truc/gli#60]
`load_dds` fails to load [this texture](https://bitbucket.org/rmsundaram/tryouts/src/master/CG/Terrain/QuadTree/data/rock.dds) with the following properties (generated using [`ddsnfo`](https://gist.github.com/legends2k/97584e4c576d7b5e0dcf))

```
DDPF_RGBAPIXELS
Uncompressed Texture
Size:              512 × 512 pixels
Stride/Pitch:      2048 bytes
Channels:          RGB, Alpha
Bit Count:         32
R Mask:            0x000000ff
G Mask:            0x0000ff00
B Mask:            0x00ff0000
Alpha Mask:        0xff000000
Mipmaps:           10
```

All the mask checking cases under `case 32:` fail and hence the format remains `gli::FORMAT_INVALID`. However, in the formats that gets listed in `format.hpp` that may match

* `RGBA8_UNORM`
* `RGBA8_SNORM`
* `RGBA8_UINT`
* `RGBA8_SINT`
* `RGBA8_SRGB`

except the first everything are for compressed textures with FourCC and thus have masks set to `0`. Only the first one has a non-trivial mask but that isn't matching either.

This texture gets loaded perfectly by the older GLI 0.5.1.1.

**Comment by Groovounet** [comment]
This issue is fixed in master branch for next release.

By the way, what tool did you use to generate this texture? I noticed that PvrTexTool could not open it either.

Thanks for contributing!
Christophe

**Comment by legends2k** [comment]
I got that file from [XNA 3.0 Game Programming Recipes](ttp://amzn.com/143021855X)'s author's site on the [terrain rendering](http://www.riemers.net/eng/Tutorials/XNA/Csharp/series4.php).

Thanks for both GLM and GLI!
Sundaram
