### ISSUE TITLE
Add install target on makefiles and ability to not compile tests

### ISSUE THREAD

**Issue by JesseTG** [g-truc/gli#64]
Just like GLM; I don't always want to build tests, but I *do* want to install gli to `/usr/local/include` or something.

**Comment by Groovounet** [comment]
I added the installer based on GLM CMake implementation which I didn't do personally so I hope it works. \o/

Thanks for contributing,
Christophe

**Comment by JesseTG** [comment]
I can do `make install` just fine, thanks!  However, I still don't see a way to not build the tests.
