### ISSUE TITLE
Incorrect format for DXT1 textures with single-bit alpha

### ISSUE THREAD

**Issue by Armada651** [g-truc/gli#68]
When loading a DXT1 texture with single-bit alpha GLI will incorrectly translate it to the `GL_COMPRESSED_RGB_S3TC_DXT1_EXT` internal format instead of `GL_COMPRESSED_RGBA_S3TC_DXT1_EXT`.

This breaks the alpha channel of the texture. It seems that the appropriate format is supported: https://github.com/g-truc/gli/blob/master/gli/core/dx.inl#L151

But this internal format is never used because the Pixel Format flags are not checked in `dx::find`: https://github.com/g-truc/gli/blob/master/gli/core/dx.inl#L280

**Comment by Groovounet** [comment]
Could you provide the texture?

Thanks for reporting!
Christophe

**Comment by Armada651** [comment]
This texture is part of the Stalker game series, so copyright is held by GSC Game World:

https://www.dropbox.com/s/qb56mbtqxmqjf6x/trees_vetkagreen1.dds?dl=0

**Comment by Armada651** [comment]
Note that transparency for DXT1 textures is not defined in the header, instead it is specified that:

> The 1-bit alpha format is distinguished from the opaque format by comparing the two 16-bit color values stored in the block. They are treated as unsigned integers. If the first color is greater than the second, it implies that only opaque texels are defined.

Source: https://msdn.microsoft.com/en-us/library/windows/desktop/bb147243%28v=vs.85%29.aspx

**Comment by Armada651** [comment]
Apparently I'm not the only one facing this problem: https://github.com/g-truc/gli/pull/58#issuecomment-141755926

**Comment by Armada651** [comment]
I think the easiest (and probably only) solution is to always assume DXT1 textures are RGBA. This will work fine with RGB textures, since they'll be opaque anyway.

**Comment by Armada651** [comment]
I've already looked at the flags which you're trying to debug, that is what I tried first.

The only conclusion you'll reach by debugging the issue is that the `DDPF_ALPHAPIXELS` flag is missing in nearly all DXT1 textures with alpha blocks.

So it must be that all those DXT1 textures are invalid and there is some unknown specification that specifies DXT1 textures without the `DDPF_ALPHAPIXELS` flag must interpret the alpha bit as Black. If you can ever find that specification let me know.
