### ISSUE TITLE
How come the manual is in DOCX format?

### ISSUE THREAD

**Issue by JesseTG** [g-truc/gli#74]
This goes for [`glm`](https://github.com/g-truc/glm), too.  I think it'd be a better fit for LaTeX or Markdown (and, if you insist, a generated PDF thereof).

- DOCX is not plain text, and thus more difficult to diff and contribute to.
- Syntax highlighting is pretty much free (I bet you had to highlight it manually)
- No need to focus on styling, just on content
- It can be read in-browser (but I'm sure there's a way to generate a PDF)

I'll send in a PR of this if you'd like.

**Comment by Groovounet** [comment]
Like most of things, because of time. I considered Asscidoc because it's what Khronos is using for Vulkan but I just didn't investigate the tool enough to figure out whether it's a good fit or not.

**Comment by JesseTG** [comment]
If I were to send in a pull request that converted the docs for `gli` (and `glm` as well) into a plain-text format that provided the following:

- Intra-document hyperlinks (e.g. table of contents)
- Syntax highlighting and proper monospace fonts for it
- Easy way to convert to a PDF
- Images

...would you accept it?

**Comment by Groovounet** [comment]
I can't guarantee that, there is a lot to consider and I haven't done that work. Some questions:
- Which tools?
- Which outputs? HTML and PDF? (I think if the output is only PDF, then it's not worth (cost == time) changing from docx. 
- Windows / Linux / OSX?
- Easy to build?

If you want to do this work, I would advice to do it a step at a time. 
1/ To integrate the tools, make sure it's cross platform, working and easy to use. Add a CMake target to build the documentation? 
2/ Write the documentation

By the way, "DOCX is not plain text, and thus more difficult to diff and contribute to." is not correct. It's plain text, can be versioned hence easy(ish) enough to contribute. ".doc" are opaque formats.

**Comment by JesseTG** [comment]
That's odd.  `cat gli.docx` doesn't return readable text for me.

As for tools:

- I'm mostly set on Markdown, but open to other options.
- Still looking into an easy way to create HTML from Markdown, but I'm sure one exists.
- For PDFs, go to `gitprint.com/<path to the Markdown file in your repo>`.  [This is what `gli`'s `README.md` looks like on GitPrint, for instance.](https://gitprint.com/g-truc/gli/blob/master/readme.md)  (And [`glm`'s](https://gitprint.com/g-truc/glm/blob/master/readme.md).)  You won't even have to include it in the repo; just link to it in the documentation itself!

Also, I wouldn't be writing new documentation, just porting the existing `gli.docx` (and `glm.docx`).

**Comment by Groovounet** [comment]
Erm, yes, it looks like a binary. I think there is a way, I'll double check this.

So why Markdown and not something else? 

Both PDF looks pretty buggy/ugly... (URLs displayed next to the caption, some wrong auto-formatting in the release note, etc) Why? Can it be fixed?

Personally, I am not a big fan of solutions that requires to be online. There are a lot of time where we are not online that are great opportunity to do hobby project work. Trains, flights, café, etc.. Half the work I did for the community was probably while commuting to work!

**Comment by JesseTG** [comment]
How about LaTeX?

**Comment by Groovounet** [comment]
This said if only the export to PDF requires to be online, I think it's just fine.

**Comment by Groovounet** [comment]
Erm, I don't know much LaTeX but it's not famous to be easy. This said, It's supposed to be robust.

I think it's going to be a hard sell to replace word by LaTeX.

**Comment by JesseTG** [comment]
I'll try it and let you know.  I'm screwing around with the manual on Overleaf (online LaTeX editor) right now, and so far it's not that hard.

**Comment by Groovounet** [comment]
Sounds good.

**Comment by JesseTG** [comment]
Wow, writing LaTeX by hand is actually kind of fun.  Why the hell didn't I start doing this as a freshman!?

**Comment by JesseTG** [comment]
I'll move this to https://github.com/g-truc/glm/issues/454
