### ISSUE TITLE
build error on msvc 2015 x64

### ISSUE THREAD

**Issue by Tarcontar** [g-truc/gli#75]
uint32 ambiguous Symbol -> convert_func.hpp lines 255, 273, 399, 417, 435, 460, 485, 503
could be unsigned int uint32 or glm::uint32

**Comment by feliwir** [comment]
I can confirm this error

**Comment by Groovounet** [comment]
What version of GLI are you using?

**Comment by feliwir** [comment]
I am using the github master branch. The error only occurs in 64-bit build

**Comment by Groovounet** [comment]
MSVC 2015 x64 is pretty much my default dev environment but I couldn't reproduce the issue. 

I guess there is something specific to the way you build with GLI. 

Would it be possible to have a repro project?

Maybe, I are using "using namespace" in you code?

**Comment by feliwir** [comment]
Problem resolved itself. Seems like there was a conflict with a different library we used (we were using "using namespace").
