### ISSUE TITLE
`kueken7_rgba_astc8x5_srgb.ktx` params

### ISSUE THREAD

**Issue by elect86** [g-truc/gli#81]
When I try to load `kueken7_rgba_astc8x5_srgb.ktx` with

glCompressedTexSubImage2D(TARGET_2D, level, 0, 0, 256, 256, 
INTERNAL_SRGB8_ALPHA8_ASTC_8x5(0x93D5), //GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR
size: 34592, data);

I get 

source: GL_DEBUG_SOURCE_API, type: GL_DEBUG_TYPE_ERROR, id: 1281, severity: GL_DEBUG_SEVERITY_HIGH, messageLog: GL_INVALID_VALUE error generated.

From the api doc, GL_INVALID_VALUE is generated if imageSize is not consistent with the format, dimensions, and contents of the specified compressed image data.

Where is the error? Data size?

**Comment by elect86** [comment]
Same `kueken7_rgba_astc12x12_srgb.ktx`

glCompressedTexSubImage2D(TARGET_2D, level, 0, 0, 256, 256,
INTERNAL_SRGB8_ALPHA8_ASTC_12x12
size: 9200, data);

**Comment by Groovounet** [comment]
Which GPU?

**Comment by elect86** [comment]
gtx 680

**Comment by Groovounet** [comment]
Not supported by that GPU. GL_KHR_texture_compression_astc_ldr must be supported.

**Comment by elect86** [comment]
Then nvidia must have been provide software emulation only for the 4x4 since `kueken7_rgba_astc4x4_srgb` dds and ktx work..

Thanks
