### ISSUE TITLE
Support Vulkan texture formats.

### ISSUE THREAD

**Issue by feliwir** [g-truc/gli#85]
Now with vulkan specification released it would be nice to have a VK.translate that returns the Vulkan image format . Is this a planned feature?

**Comment by Groovounet** [comment]
No need. \o/ 

With GLI 0.8 texture::format() will return an ID that is a direct mapping to Vulkan formats. 

Enjoy! :)

**Comment by feliwir** [comment]
Awesome :+1: thanks

**Comment by JesseTG** [comment]
So this can be closed, right?
