### ISSUE TITLE
GLI 0.8 doesn't build with a release version of GLM

### ISSUE THREAD

**Issue by Groovounet** [g-truc/gli#88]
email from Guus:

> I'm preparing Debian packages for GLI. I encountered an issue though;
> GLI contains a copy of GLM in external/glm, but this copy has functions
> that are not in the latest release of GLM itself. When I try to compile
> GLI with GLM 0.9.7.3, I get the following error:
> 
> In file included from /home/guus/gli/gli-0.8.0.0/./gli/sampler2d.hpp:9:0,
>                  from /home/guus/gli/gli-0.8.0.0/test/core/convert_sampler1d.cpp:1:
> /home/guus/gli/gli-0.8.0.0/./gli/core/convert_func.hpp: In static member function ‘static glm::tvec4<retType, P> gli::detail::convertFunc<textureType, retType, T, P, vecType, (gli::detail::convertMode)2u, true>::fetch(const textureType&, const typename textureType::extent_type&, typename textureType::size_type, typename textureType::size_type, typename textureType::size_type)’:
> 
> /home/guus/gli/gli-0.8.0.0/./gli/core/convert_func.hpp:196:33: error: ‘compNormalize’ was not declared in this scope
>     return make_vec4<retType, P>(compNormalize<retType>(access::load(Texture, TexelCoord, Layer, Face, Level)));
> 
> Indeed, compNormalize is in external/glm/glm/gtx/component_wise.hpp, but
> not in 0.9.7.3's component_wise.hpp.

**Comment by Groovounet** [comment]
My plan is to bring the missing GLM code in GLI 0.8.1 because GLM 0.9.8 is not ready.

Thanks for reporting this issue!

**Comment by Groovounet** [comment]
After some experiments, it's going to be hard to use GLM 0.9.7 with GLI 0.8.X. I'll have to ship GLM 0.9.8 first...

**Comment by feliwir** [comment]
I've encountered the same problem today. Using glm 0.9.7.4 with gli 0.8.1.0 make our build slave fail. Any idea when glm 0.9.8 is ready?

**Comment by Groovounet** [comment]
This issue is fixed. GLI 0.8.1.1 revision rely on the release version of GLM 0.9.8.0.

Thanks,
Christophe
