### ISSUE TITLE
3D DDS saving issues

### ISSUE THREAD

**Issue by alex-hrin** [g-truc/gli#91]
Saving DDS files that contain 3D textures and use a DX10 header results in the header being registered for a 2D texture and the saved file being recognised as a 2D texture by various viewers.
Reproducible with:
```c++
gli::texture3d tex3D = gli::texture3d(gli::format::FORMAT_RGBA32_UINT_PACK32, gli::extent3d(32, 32, 32), 1);
for (size_t z = 0; z < 32; z++) {
	for (size_t y = 0; y < 32; y++) {
		for (size_t x = 0; x < 32; x++, j++) {
			tex3D.store(gli::extent3d(x, y, z), 0, glm::uvec4(0xFFFFFF * x, 0xFFFFFF * y, 0xFFFFFF * z, 0xFFFFFFFF));
		}
	}
}
gli::save(tex3D, std::string("result.dds"));
```
I've narrowed it down a difference in the enum value ordering from `gli::target` in target.hpp compared to `static d3d10_resource_dimension Table[]` inside `gli::detail::inline d3d10_resource_dimension get_dimension(gli::target const& Target)` from save_dds.inl

Placing D3D10_RESOURCE_DIMENSION_TEXTURE3D before the 2D rect textures to match the `gli::target` ordering seems to fix it.
Hope this helps.

Cheers

**Comment by Groovounet** [comment]
Hi,

This issue is fixed in master branch for GLI 0.8.1 release.

Thanks for contributing!
Christophe
