### ISSUE TITLE
Incorrect external format and swizzle on some dds files

### ISSUE THREAD

**Issue by timon37** [g-truc/gli#92]
The file [gli_bad_BGR_and_swizzle.dds.zip](https://github.com/g-truc/gli/files/174031/gli_bad_BGR_and_swizzle.dds.zip) is processed correctly by dx9, and even gimp opens it correctly.
But when loading with gli (using PROFILE_GL33), we're getting a GL_BGRA external format and a swizzle-mask [GL_BLUE, GL_GREEN, GL_RED, GL_ONE].
This results in a double color flip which is incorrect.

The correct behaviours would be:
1. int-format: GL_RGB, ext-format: GL_BGRA, swizzle: [ RED, GREEN, BLUE, ONE]
2. int-format: GL_RGB, ext-format: GL_RGBA, swizzle: [ BLUE, GREEN, RED, ONE]
Personally I prefer 1.

**Comment by Groovounet** [comment]
Erm, this should be fixed in the master branch and solution 2/ was selected for PROFILE_GL33. However, for PROFILE_GL32, swizzle operators are not available to solution 1/ is used in this case, not sure what swizzle return in that case, but it should not be used. Certainly all this needs to be documented...

**Comment by Groovounet** [comment]
You were right, BGRX format was not handle correctly with PROFILE_GL33.

This is fixed for GLI 0.8.1 release.

The difference between profiles:
- PROFILE_GL33: always used texture swizzle when the format is not RGBA
- PROFILE_GL32: texture swizzle isn't supported, fallback to BGRA format that can be expressed this way, too bad for the other (luminance alpha which isn't supported at all in GL 3.2)

Thanks for contributing!
Christophe
