### ISSUE TITLE
Fails to build on OS X 10.11

### ISSUE THREAD

**Issue by nathanielwarner** [g-truc/gli#97]
CMake generates the unix makefile without error, but the make command fails:
`In file included from /Users/nathanielwarner/Downloads/gli/test/core/core_clear.cpp:4:
In file included from /Users/nathanielwarner/Downloads/gli/./gli/clear.hpp:46:
/Users/nathanielwarner/Downloads/gli/./gli/./core/clear.inl:28:12: error: use
      'template' keyword to treat 'clear' as a dependent template name
                        Texture.clear<gen_type>(LayerIndex, FaceIndex, B...
                                ^
                                template 
/Users/nathanielwarner/Downloads/gli/./gli/./core/clear.inl:45:12: error: use
      'template' keyword to treat 'clear' as a dependent template name
                        Texture.clear<gen_type>(LayerIndex, BaseFace + F...
                                ^
                                template 
/Users/nathanielwarner/Downloads/gli/./gli/./core/clear.inl:62:12: error: use
      'template' keyword to treat 'clear' as a dependent template name
                        Texture.clear<gen_type>(LayerIndex + BaseLayer, ...
                                ^
                                template 
3 errors generated.`

**Comment by Groovounet** [comment]
This issue is fixed in GLI 0.8.1.1

Thanks for reporting,
Christophe
