### ISSUE TITLE
Saved ktx files dont open with libktx

### ISSUE THREAD

**Issue by Sibras** [g-truc/gli#98]
Files created by GLI in ktx format do not open with the official libktx as it will generate an error when passing the ktx header. This is due to libktx requiring the number of faces in a texture to be either 1 or 6. However GLI outputs a header with 0 or 6 faces.
see save_ktx.inl line 59:
Header.NumberOfFaces = is_target_cube(Target) ? static_cast<std::uint32_t>(Texture.faces()) : 0;

changing the above from 0 to 1 fixes the error.

**Comment by Groovounet** [comment]
Well well well, if that's not an unfortunate bug.

This issue is fixed in master branch for the next GLI 0.8.1.1 release.
Thanks for contributing,
Christophe
