### ISSUE TITLE
Static_assert for dds loading failing with master glm

### ISSUE THREAD

**Issue by feliwir** [g-truc/gli#99]
Hey i have this failing with msvc 2015 - 64 bit and the glm for master:
static_assert(sizeof(dds_header) == 124, "DDS Header size mismatch");
(line 71 in load_dds.inl).

Compiler is saying the size is 144.

**Comment by Groovounet** [comment]
Hi,

This is a known issue that I am currently fixing. This is due to a GLM regression.

Thanks,
Christophe

**Comment by Groovounet** [comment]
Hi, this issue should be fixed

Thanks for reporting!
Christophe
